/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sinboha_CONSTANTS_H
#define sinboha_CONSTANTS_H

#include "sinboha_types.h"

namespace SINBOHA_NET {

class sinbohaConstants {
 public:
  sinbohaConstants();

};

extern const sinbohaConstants g_sinboha_constants;

} // namespace

#endif
