/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sinboha_constants.h"

namespace SINBOHA_NET {

const sinbohaConstants g_sinboha_constants;

sinbohaConstants::sinbohaConstants() {
}

} // namespace

